cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history/', views.order_history, name='order_history'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home_view, name='home_page'),
    path('<str:newsletter_message>', views.home_view, name='home_page'),
    path('search/', views.search_view, name='search_page'),
    path('contact/', views.contact_view, name='contact_page'),
    path('products/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label=_('Quantity'))
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

coupons/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class CouponApplyForm(forms.Form):
    code = forms.CharField(label=_('Coupon'))

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    print(request.session.items())
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = None
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/cart-details.html',
                           {'cart': cart,
                            'coupon_apply_form': coupon_apply_form,
                            'username': username})

templates/cart/cart-details.html
{% extends "shop/product/base.html" %}

{% load static %}

{% block title %}
    Ogani | Cart
{% endblock %}

{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <div class="hero__search">
                        <div class="hero__search__form m-r-10">
                            <form action="{% url 'shop:search_page' %}" method="get">
                                <input type="text" placeholder="What do yo u need?" name="keyword">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Ogani Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="/">Home</a>
                            <span>Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr>
                                            <td class="shoping__cart__item">
                                                <img src="{% if product.image %}{{ product.image.url }}
                                                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt=""
                                                    style="height: 101px; width: 100px">
                                                <h5>{{ product.name }}</h5>
                                            </td>
                                            <td class="shoping__cart__price">
                                                ₦{{ item.price }}
                                            </td>
                                            <td class="shoping__cart__quantity">
                                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                    <div class="quantity">
                                                        <div class="pro-qty">
                                                            <input type="text"
                                                                   value="{{ item.quantity }}" name="quantity"
                                                                   required id="id_quantity">
                                                        </div>
                                                    </div>
                                                    {{ item.update_quantity_form.override }}
                                                    <input type="submit" class="primary-btn cart-btn" value="Update"
                                                        style="border-radius: 5px; margin-top: 5px; padding: 7px 20px;
                                                        border: 2px solid #b3b3b3">
                                                    {% csrf_token %}
                                                </form>
                                            </td>
                                            <td class="shoping__cart__total">
                                                ₦{{ item.total_price }}
                                            </td>
                                            <td class="shoping__cart__item__close">
                                                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                                    <button type="submit" class="no-design-button icon_close">

                                                    </button>
                                                    {% csrf_token %}
                                                </form>
                                            </td>
                                        </tr>
                                    {% endwith %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="{% url "shop:product_list" %}" class="primary-btn cart-btn cart-btn-right">CONTINUE SHOPPING</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Discount Codes</h5>
                            <form action="{% url "coupons:apply" %}" method="post">
                                {% csrf_token %}
                                <input type="text" placeholder="Enter your coupon code" name="code" required id="id_code">
                                <button type="submit" class="site-btn">APPLY COUPON</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            {% if cart.coupon %}
                                <li>Subtotal <span>₦{{ cart.get_total_price|floatformat:2 }}</span></li>
                                {% with code=cart.coupon.code discount=cart.coupon.discount %}
                                    <li>"{{ code }}" coupon ({{ discount }}% off)
                                        <span>- ₦{{ cart.get_discount|floatformat:2 }}</span>
                                    </li>
                                {% endwith %}
                            {% endif %}
                            <li>Total <span>₦{{ cart.get_total_price_after_discount|floatformat:2 }}</span></li>
                        </ul>
                        <a href="{% url "orders:order_create" %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->
{% endblock %}