cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history/', views.order_history, name='order_history'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home_view, name='home_page'),
    path('<str:newsletter_message>', views.home_view, name='home_page'),
    path('search/', views.search_view, name='search_page'),
    path('contact/', views.contact_view, name='contact_page'),
    path('products/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

orders/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator, \
                                   MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from shop.models import Product
from coupons.models import Coupon
from django.conf import settings


class Order(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(_('first name'), max_length=50)
    last_name = models.CharField(_('last name'), max_length=50)
    email = models.EmailField(_('e-mail'))
    phone = models.CharField(_('phone number'), max_length=11, null=True)
    address = models.CharField(_('address'), max_length=500)
    postal_code = models.CharField(_('postal code'), max_length=20)
    city = models.CharField(_('city'), max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    order_notes = models.TextField(default='', blank=True)
    braintree_id = models.CharField(max_length=150, blank=True)
    coupon = models.ForeignKey(Coupon,
                               related_name='orders',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100))


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity


class ShippingAddress(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    street_name = models.CharField(max_length=100)
    house_no = models.CharField(max_length=30)
    town = models.CharField(max_length=50)
    state = models.CharField(max_length=15)
    post_code = models.CharField(max_length=10)
    phone = models.CharField(max_length=11)
    email = models.EmailField()

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'postal_code', 'city', 'email', 'phone', 'order_notes']

orders/views.py
import weasyprint
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.template.loader import render_to_string
import json
from cart.cart import Cart
from .models import OrderItem, Order
from .forms import OrderCreateForm
# from .tasks import order_created
from uuid import uuid4
from .models import ShippingAddress


def order_create(request):
    cart = Cart(request)
    if len(cart) == 0:
        return HttpResponseRedirect(reverse('shop:product_list'))

    if request.user.is_authenticated:
        username = request.user.username
        try:
            address = ShippingAddress.objects.get(owner=request.user)
        except ShippingAddress.DoesNotExist:
            address = None
    else:
        username = None
        address = None

    if request.method == 'POST':
        if len(cart) == 0:
            return JsonResponse({'message': 'Cart is empty'}, status=404)
        form = OrderCreateForm(json.loads(request.body))
        if form.is_valid():
            order = form.save(commit=False)
            order.braintree_id = uuid4().hex
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount

            if request.user.is_authenticated:
                order.owner = request.user
                try:
                    ShippingAddress.objects.get(owner=request.user, post_code=order.postal_code)
                except ShippingAddress.DoesNotExist:
                    # Save Billing Address
                    ShippingAddress.objects.create(owner=request.user,
                                                   first_name=order.first_name,
                                                   last_name=order.last_name,
                                                   street_name=order.address.split('~')[1],
                                                   house_no=order.address.split('~')[0],
                                                   town=order.city,
                                                   state=order.address.split('~')[2],
                                                   post_code=order.postal_code,
                                                   phone=order.phone,
                                                   email=order.email)

            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])

            # launch asynchronous task
            # order_created.delay(order.id)
            # redirect for payment
            # save session id
            request.session['order_id'] = order.id
            return JsonResponse({'message': 'order saved successfully',
                                 'data': {
                                     'key': settings.PAYSTACK_PUBLIC_KEY,
                                     'firstname': order.first_name,
                                     'lastname': order.last_name,
                                     'email': order.email,
                                     'amount': cart.get_total_price_after_discount(),
                                     'order_ref': order.braintree_id
                                 },
                                 }, status=200)
        else:
            return JsonResponse({'message': 'invalid form input'}, status=400)
    else:
        return render(request,
                      'orders/order/checkout.html',
                      {'cart': cart,
                       'username': username,
                       'address': address})


def order_history(request):
    if request.user.is_authenticated:
        username = request.user.username
        saved_orders = Order.objects.filter(owner=request.user)
        items = []
        total = 0
        for order in saved_orders:
            update_date = order.updated.date().strftime('%D')
            update_time = order.updated.time().strftime('%T')

            for item in OrderItem.objects.filter(order=order):
                total += item.get_cost()
                items.append({'name': item.product.name,
                              'price': item.price,
                              'quantity': item.quantity,
                              'total_price': item.get_cost(),
                              'image': item.product.image.url,
                              'update_time': update_time,
                              'update_date': update_date,
                              'username': username})

        return render(request,
                      'orders/order/purchase_history.html',
                      {'items': items,
                       'total_amount': total})
    else:
        return HttpResponse({}, status=401)


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
        stylesheets=[weasyprint.CSS(
            settings.STATIC_ROOT + 'css/pdf.css')])
    return response

templates/orders/order/checkout.html
{% extends "shop/product/base.html" %}

{% load static %}

{% block title %}
    Ogani | Checkout
{% endblock %}

{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <div class="hero__search">
                        <div class="hero__search__form m-r-10">
                            <form action="{% url 'shop:search_page' %}" method="get">
                                <input type="text" placeholder="What do yo u need?" name="keyword">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                        <div class="breadcrumb__option">
                            <a href="/">Home</a>
                            <span>Checkout</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

        <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6><span class="icon_tag_alt"></span> Have a coupon? <a href="/cart/">Click here</a> to enter your code
                    </h6>
                </div>
            </div>
            <div class="checkout__form">
                <p class="error-panel" style="display: none"></p>
                <h4>Billing Details</h4>
                <form data-url="/orders/create/" method="POST" id="checkout-form">
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Fist Name<span>*</span></p>
                                        <input type="text" name="first_name" required id="id_first_name" maxlength="50"
                                        value="{{ address.first_name }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text" name="last_name" required id="id_last_name" maxlength="50"
                                        value="{{ address.last_name }}">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" placeholder="Street Address" class="checkout__input__add"
                                       name="street_address" required id="id_street" value="{{ address.street_name }}">
                                <input type="text" placeholder="Apartment, suite, unit etc (optional)"
                                       name="apartment_no" required id="id_apartment_no" value="{{ address.house_no }}">
                            </div>
                            <div class="checkout__input">
                                <p>Town/City<span>*</span></p>
                                <input type="text" name="city_town" required id="id_city_town" maxlength="50"
                                value="{{ address.town }}">
                            </div>
                            <div class="checkout__input">
                                <p>State<span>*</span></p>
                                <input type="text" name="state" required id="id_state" maxlength="15" value="{{ address.state }}">
                            </div>
                            <div class="checkout__input">
                                <p>Postcode / ZIP<span>*</span></p>
                                <input type="text" name="post_zip" required id="id_post_zip" maxlength="10"
                                       value="{{ address.post_code }}">
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Phone<span>*</span></p>
                                        <input type="number" name="phone_number" required id="id_phone_number"
                                               maxlength="11" value="{{ address.phone }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="email" name="email" required id="id_email" maxlength="254"
                                        value="{{ address.email }}">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Order notes</p>
                                <input type="text" name="order_notes" required id="id_notes"
                                    placeholder="Notes about your order, e.g. special notes for delivery."  >
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h4>Your Order</h4>
                                <div class="checkout__order__products">Products <span>Total</span></div>
                                <ul>
                                    {% for item in cart %}
                                        <li>
                                        {{ item.quantity }}x {{ item.product.name }}
                                        <span>₦{{ item.total_price|floatformat:2 }}</span>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div class="checkout__order__subtotal">
                                    Subtotal <span>₦{{ cart.get_total_price|floatformat:2 }}</span>
                                </div>
                                {% if cart.coupon %}
                                    <div class="checkout__order__total" style="border-bottom: 1px solid #e1e1e1;">
                                        Discount <span>- ₦{{ cart.get_discount|floatformat:2 }}</span>
                                    </div>
                                {% endif %}
                                <div class="checkout__order__total">
                                    Total <span>{{ cart.get_total_price_after_discount|floatformat:2 }}</span>
                                </div>
                                <button type="submit" class="site-btn" id="submit-btn">PLACE ORDER</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block script %}
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="{% static 'js/submit_checkout.js' %}"></script>
{% endblock %}

templates/orders/order/pdf.html
<html>
<body>
  <h1>My Shop</h1>
  <p>
    Invoice no. {{ order.id }} <br/>
    <span class="secondary">
      {{ order.created|date:"M d, Y" }}
    </span>
  </p>

  <h3>Bill to</h3>
  <p>
    {{ order.first_name }} {{ order.last_name }}<br>
    {{ order.email }}<br>
    {{ order.address }}<br>
    {{ order.postal_code }}, {{ order.city }}
  </p>

  <h3>Items bought</h3>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle "1" "2" %}">
          <td>{{ item.product.name }}</td>
          <td class="num">₦{{ item.price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">₦{{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      <tr class="total">
        <td colspan="3">Total</td>
        <td class="num">₦{{ order.get_total_cost }}</td>
      </tr>
    </tbody>
  </table>

  <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
    {% if order.paid %}Paid{% else %}Pending payment{% endif %}
  </span>
</body>
</html>

templates/orders/order/purchase_history.html
{% extends "shop/product/base.html" %}

{% load static %}

{% block title %}
    Ogani | Cart
{% endblock %}

{% block content %}
{#    <!-- Hero Section Begin -->#}
{#    <section class="hero hero-normal">#}
{#        <div class="container">#}
{#            <div class="row justify-content-center">#}
{#                <div class="col-lg-2"></div>#}
{#                <div class="col-lg-8">#}
{#                    <div class="hero__search">#}
{#                        <div class="hero__search__form m-r-10">#}
{#                            <form action="#">#}
{#                                <input type="text" placeholder="What do you need?">#}
{#                                <button type="submit" class="site-btn">SEARCH</button>#}
{#                            </form>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{#    <!-- Hero Section End -->#}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Ogani History</h2>
                        <div class="breadcrumb__option">
                            <a href="/">Home</a>
                            <span>Purchase History</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Purchase Date</th>
                                    <th>Purchase Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in items %}
                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img src="{% if item.image %}{{ item.image }}
                                                    {% else %}{% static "img/no_image.png" %}{% endif %}" alt=""
                                                style="height: 101px; width: 100px">
                                            <h5>{{ item.name }}</h5>
                                        </td>
                                        <td class="shoping__cart__price">
                                            ₦{{ item.price }}
                                        </td>
                                        <td class="shoping__cart__quantity">
                                            <div class="quantity">
                                                <p>{{ item.quantity }}</p>
                                            </div>
{#                                                <input type="submit" class="primary-btn cart-btn" value="Update"#}
{#                                                    style="border-radius: 5px; margin-top: 5px; padding: 7px 20px;#}
{#                                                    border: 2px solid #b3b3b3">#}
                                        </td>
                                        <td class="shoping__cart__total">
                                            ₦{{ item.total_price }}
                                        </td>
                                        <td>
                                            {{ item.update_date }}
                                        </td>
                                        <td>
                                            {{ item.update_time }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <h4 class="primary-btn cart-btn cart-btn-right" style="font-size: 17px">
                            Total:
                            <span style="font-size: 17px; color: #dd2222;">₦{{ total_amount }}</span></h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->

{% endblock %}