cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home_view, name='home_page'),
    path('<str:newsletter_message>', views.home_view, name='home_page'),
    path('search/', views.search_view, name='search_page'),
    path('contact/', views.contact_view, name='contact_page'),
    path('products/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                          db_index=True)
    slug = models.SlugField(max_length=200,
                          db_index=True,
                          unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.CharField(blank=True, max_length=250)
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Contact(models.Model):
    contact_name = models.CharField(max_length=50)
    email_address = models.EmailField()
    message = models.TextField()

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label=_('Quantity'))
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

shop/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product
from .forms import ContactForm
from django.views.decorators.http import require_GET
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def product_list(request, category_slug=None):
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = None
    category = None
    page_number = request.GET.get('page')

    categories = Category.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = Product.objects.filter(category=category, available=True)
    else:
        products_list = Product.objects.filter(available=True)

    paginator = Paginator(products_list, 9)

    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request,
                  'shop/product/product-list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'username': username,
                   'page_numbers': [str(number) for number in range(1, paginator.num_pages + 1)],
                   'active_page': page_number})


def product_detail(request, id, slug):
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = None
    product = get_object_or_404(Product,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product/product-details.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'username': username})


def home_view(request, newsletter_message=None):
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = None
    categories = Category.objects.all()
    return render(request,
                  'shop/product/home.html',
                  {'categories': categories,
                   'username': username,
                   'newsletter_response': newsletter_message})


@require_GET
def search_view(request):
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = None

    search_phrase = request.GET.get('keyword')
    if search_phrase:
        matching_products = Product.objects.filter(name__contains=search_phrase)
        return render(request,
                      'shop/product/search.html',
                      {'products': matching_products,
                       'username': username,
                       'search_phrase': search_phrase})
    else:
        # return reverse('shop:home_page')
        return render(request,
                      'shop/product/search.html',
                      {'username': username})


def contact_view(request):
    if request.method == 'GET':
        return render(request, 'shop/contact.html', {})
    elif request.method == 'POST':
        contact_form = ContactForm(request.POST)

        if contact_form.is_valid():
            contact_form.save()
            return render(request, 'shop/contact.html',
                          {'message': 'Information saved an agent will contact you shortly'})
        else:
            return render(request, 'shop/contact.html',
                          {'message': contact_form.errors.values()})

templates/shop/product/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Ogani Home Page">
        <meta name="keywords" content="Ogani">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

        <!-- Css Styles -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    </head>

    <body>
        <!-- Page Preloader -->
{#        <div id="preloder">#}
{#            <div class="loader"></div>#}
{#        </div>#}

        <!-- Humberger Begin -->
        <div class="humberger__menu__overlay"></div>
        <div class="humberger__menu__wrapper">
            <div class="humberger__menu__logo">
                <a href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
            </div>
            <nav class="humberger__menu__nav mobile-menu">
                <ul>
                    <li {% if products is None %} class="active" {% endif %}><a href="/">Home</a></li>
                    <li {% if products %} class="active" {% endif %}><a href="{% url 'shop:product_list' %}">Shop</a></li>
                    <li><a href="{% url 'shop:contact_page' %}">Contact</a></li>
                </ul>
            </nav>
            <div id="mobile-menu-wrap"></div>
        </div>
        <!-- Humberger End -->

        <!-- Header Section Begin -->
        <header class="header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="header__logo">
                            <a href="/"><img src="{% static 'img/logo.png' %}" alt="Logo"></a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <nav class="header__menu">
                            <ul>
                                <li {% if products is None %} class="active" {% endif %}><a href="/">Home</a></li>
                                <li {% if products %} class="active" {% endif %} ><a href="{% url 'shop:product_list' %}">Shop</a></li>
                                <li><a href="{% url 'shop:contact_page' %}">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-3">
                        <div class="header__cart">
                            <ul>
                                {% with total_items=cart|length %}
                                    {% if total_items > 0 %}
                                        <li>
                                            <a href="{% url "cart:cart_detail" %}">
                                                <i class="fa fa-shopping-bag"></i>
                                                <span>{{ total_items }}</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-shopping-bag"></i>
                                                <span>{{ total_items }}</span>
                                            </a>
                                        </li>
                                    {% endif %}

                                {% endwith %}
                            </ul>
                            <div class="header__top__right__auth">
                                {% if username %}
                                    <div class="dropdown show">
                                        <a class="btn dropdown-toggle" href="#" role="button"
                                         id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                         aria-expanded="false">
                                        <i class="fa fa-user"></i> {{ username }}
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <a href="/orders/history/" style="text-align: center; font-size: 1rem">
                                                Purchase History
                                            </a>
                                            <form method="post" action="{% url 'account_logout' %}">
                                              {% csrf_token %}
                                              {% if redirect_field_value %}
                                                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                                              {% endif %}
                                              <button class="dropdown-item" type="submit">Logout</button>
                                            </form>
                                        </div>
                                    </div>
                                {% else %}
                                    <a href="/accounts/login/"><i class="fa fa-user"></i> Login</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="humberger__open">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
        </header>
        <!-- Header Section End -->
        {% block content %}
        {% endblock %}
        <!-- Footer Section Begin -->
        <footer class="footer spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer__about">
                            <div class="footer__about__logo">
                                <a href="home.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                            </div>
                            <ul>
                                <li>Address: 25B, Admiralty Road, <br> Festac, Lagos</li>
                                <li>Phone: +234 709 261 8445</li>
                                <li>Email: hello@ogani.comm</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                        <div class="footer__widget">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12">
                        <div class="footer__widget">
                            <h6>Join Our Newsletter Now</h6>
                            <p>Get E-mail updates about our latest shop and special offers.</p>
                            {% if newsletter_response %}
                                <p style="color: #dd2222">{{ newsletter_response }}</p>
                            {% endif %}
                            <form action="/newsletter/add/" method="post">
                                {% csrf_token %}
                                <input type="text" placeholder="Enter your mail" name="email_address">
                                <input type="hidden" name="receive_email" value="true">
                                <button type="submit" class="site-btn">Subscribe</button>
                            </form>
                            <div class="footer__widget__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer Section End -->

        <!-- Js Plugins -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
                integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
                crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/jquery.slicknav.js' %}"></script>
        <script src="{% static 'js/mixitup.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        {% block script %}
        {% endblock %}
    </body>

</html>

templates/shop/product/product-details.html
{% extends "shop/product/base.html" %}

{% load static %}

{% block title %}
  Ogani | Product Details
{% endblock %}

{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <div class="hero__search">
                        <div class="hero__search__form m-r-10">
                            <form action="{% url 'shop:search_page' %}" method="get">
                                <input type="text" placeholder="What do you need?" name="keyword">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>{{ product.name }}</h2>
                        <div class="breadcrumb__option">
                            <a href="/">Home</a>
                            <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
                            <span>{{ product.name }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Details Section Begin -->
    <section class="product-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__pic">
                        <div class="product__details__pic__item">
                            <img class="product__details__pic__item--large"
                                src="{% if product.image %}{{ product.image.url }}{% else %}
                                        {% static "img/no_image.png" %}{% endif %}" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__text">
                        <h3>{{ product.name }}</h3>
                        <div class="product__details__rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                            <a href="#reviews-section">(1 reviews)</a>
                        </div>
                        <div class="product__details__price">₦ {{ product.price }}</div>
                        <p>{{ product.description|linebreaks }}</p>
                        <div class="product__details__quantity">
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                <div class="quantity" style="display: inline-block; margin-right: 10px;">
                                    <div class="pro-qty">
                                        <input type="number" value=1 min=0 name="quantity" required id="id_quantity">
                                    </div>
                                </div>
                                <input type="hidden" name="override" value="False" required id="id_override">
                                <button class="primary-btn" type="submit" style="border: none; display: inline">
                                    ADD TO CART
                                </button>
                            </form>
                        </div>
                        <ul>
                            <li><b>Availability</b> <span>In Stock</span></li>
                            <li><b>Shipping</b> <span>Usually shipped within a week <samp>Free pickup today</samp></span></li>
                            <li><b>Weight</b> <span>Less than 5kg</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="product__details__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <span class="review-link" id="reviews-section" style="font-weight: bolder; font-size: 22px">Reviews</span>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="product__details__tab__desc">
                                    <p>Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
                                        Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus
                                        suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam
                                        vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada.
                                        Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat,
                                        accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a
                                        pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula
                                        elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus
                                        et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam
                                        vel, ullamcorper sit amet ligula. Proin eget tortor risus.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Details Section End -->
{% endblock %}

templates/shop/product/product-list.html
{% extends "shop/product/base.html" %}

{% load static %}

{% block title %}
  {% if category %}Ogani | {{ category.name }}{% else %}Ogani | Shop{% endif %}
{% endblock %}

{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <div class="hero__search">
                        <div class="hero__search__form m-r-10">
                            <form action="{% url 'shop:search_page' %}" method="get">
                                <input type="text" placeholder="What do yo u need?" name="keyword">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Ogani Shop</h2>
                        <div class="breadcrumb__option">
                            <a href="/">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5">
                    <div class="sidebar">
                        <div class="sidebar__item">
                            <h4>Department</h4>
                                <ul class="department-list">
                                    <li {% if not category %}class="active-category"{% endif %}>
                                    <a href="{% url "shop:product_list" %}">All</a>
                                </li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="active-category"{% endif %}>
                                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-7">
                    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-4 col-md-5">
                                <div class="filter__sort">
                                    <span>Sort By</span>
                                    <select>
                                        <option value="0">Default</option>
                                        <option value="0">Default</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <div class="filter__found">
                                    <h6><span>{{ products | length }}</span> Products found</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                                        <ul class="product__item__pic__hover">
                                            <li>
                                                <a href="{{ product.get_absolute_url }}">
                                                    <i class="fa fa-angle-double-right"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <h6><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
                                        <h5>₦{{ product.price }}</h5>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="product__pagination">
                        {% for page_number in page_numbers %}
                            <a href="/products/?page={{ page_number }}"
                                    {% if page_number == active_page %}class="active-page-number"{% endif %}>
                                {{ page_number }}
                            </a>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Section End -->
{% endblock %}